# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=2)),
                ('school_class', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('highschool', models.CharField(max_length=100)),
                ('fourty', models.FloatField(blank=True, null=True)),
                ('ten_yard', models.FloatField(blank=True, null=True)),
                ('bench', models.FloatField(blank=True, null=True)),
                ('cone', models.FloatField(blank=True, null=True)),
                ('short_shut', models.FloatField(blank=True, null=True)),
                ('sixty', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('broad', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.School'),
        ),
    ]
