# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='player.School')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='player.School')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletic_ability', models.FloatField()),
                ('athletic_ability_desc', models.TextField()),
                ('football_intelligence', models.FloatField()),
                ('football_intelligence_desc', models.TextField()),
                ('toughness', models.FloatField()),
                ('toughness_desc', models.TextField()),
                ('play_speed', models.FloatField()),
                ('play_speed_desc', models.TextField()),
                ('pos_athletic_ability', models.FloatField()),
                ('pos_athletic_ability_desc', models.TextField()),
                ('pos_football_intelligence', models.FloatField()),
                ('pos_football_intelligence_desc', models.TextField()),
                ('pos_toughness', models.FloatField()),
                ('pos_toughness_desc', models.TextField()),
                ('pos_play_speed', models.FloatField()),
                ('pos_play_speed_desc', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('summary', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
