# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paid_neccessary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paid_neccessary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paid_neccessary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('paid_neccessary', models.BooleanField(default=True)),
            ],
        ),
    ]
